# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JotCli < Formula
  desc "A fast, context-aware notes tool for the terminal"
  homepage "https://github.com/danjdewhurst/jot-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.3.0/jot-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "59a86dc524cd45c20fb52699fa614133ff068b90fa1f050399019c30b613d055"

      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.3.0/jot-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "dd572157e48bac5cbb54e79c4f7e6f0287a4b1f9626d4d2d241ce93eb75fad25"

      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.3.0/jot-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "c471250b4e066c69ea78a60fe67678dfd405caf4aa0375c618caaa35dd129b94"
      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.3.0/jot-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "9c0ad8c3a4ce5fd04e6db3b416b8aed7084c465d2b2fbe5f76d18d5a475cec6c"
      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
  end

  test do
    assert_match "jot-cli", shell_output("#{bin}/jot-cli version")
  end
end
