# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JotCli < Formula
  desc "A fast, context-aware notes tool for the terminal"
  homepage "https://github.com/danjdewhurst/jot-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.6.0/jot-cli_0.6.0_darwin_amd64.tar.gz"
      sha256 "4e8b012740b3c75a3a71425b2279dcfd875ae2f711f0049d0167145cf4eeb540"

      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.6.0/jot-cli_0.6.0_darwin_arm64.tar.gz"
      sha256 "9e11c6046267fba8a2950c64a8ab3c5c5ff6c26dfec36eae35b146104a0f21ce"

      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.6.0/jot-cli_0.6.0_linux_amd64.tar.gz"
      sha256 "06b4745febf2d4be49a7396cfa3cd48c057e9bf331c680dbb17a9ded86144072"
      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.6.0/jot-cli_0.6.0_linux_arm64.tar.gz"
      sha256 "0006e04387cd3ac950c26c658b5c89616a80b40bf9a3a208b25ca34e05da0241"
      define_method(:install) do
        bin.install "jot-cli"
        bin.install_symlink "jot-cli" => "j"
      end
    end
  end
end
