# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jot < Formula
  desc "A fast, context-aware notes tool for the terminal"
  homepage "https://github.com/danjdewhurst/jot-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.1.0/jot_0.1.0_darwin_amd64.tar.gz"
      sha256 "ad6c1ac60417523c56bf2ae53459bdbfa56429eed7ec9b94fd930e813a5d61c0"

      define_method(:install) do
        bin.install "jot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.1.0/jot_0.1.0_darwin_arm64.tar.gz"
      sha256 "b10f42f6de629c1dc090fb23417b4b276b747dea82ccc177b342f2f94b06a3d7"

      define_method(:install) do
        bin.install "jot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.1.0/jot_0.1.0_linux_amd64.tar.gz"
      sha256 "a94e0f9ea3c5c73a5e27c7a9cc83e7021eac94fd4cb6050bd140ec25d09f795a"
      define_method(:install) do
        bin.install "jot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v0.1.0/jot_0.1.0_linux_arm64.tar.gz"
      sha256 "83b5b440fbb7028395dae2af0cc0e5dfa5af3de9cf9319accdc44fc2e4659e24"
      define_method(:install) do
        bin.install "jot"
      end
    end
  end

  test do
    assert_match "jot", shell_output("#{bin}/jot version")
  end
end
