# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.js in danjdewhurst/story-skills. Do not edit:
# the release workflow rewrites it for every release.
class StorySkills < Formula
  desc "Companion CLI for Story Skills: validate, check, and build markdown story projects"
  homepage "https://github.com/danjdewhurst/story-skills"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.18.0/story-skills_0.18.0_darwin_arm64.tar.gz"
      sha256 "d0844091a55496db26aba6b32f80b0be853248bc8ed94c277a18ad04f7a608e9"
    end
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.18.0/story-skills_0.18.0_darwin_x64.tar.gz"
      sha256 "f827461c957f7b8ef4b2bd59a85a54e9173e53476d4d0c3c98e83fedec35d13a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.18.0/story-skills_0.18.0_linux_arm64.tar.gz"
      sha256 "71992f25105b012fddb693bcf244d73eb8a4d5ad49f9d5b40781091153cf1e08"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.18.0/story-skills_0.18.0_linux_x64.tar.gz"
      sha256 "c80caf14ce29201a8a88b4da34c317259f2fced3d7a11742865a900bef0b3ee6"
    end
  end

  def install
    bin.install "story"
  end

  test do
    assert_equal "0.18.0", shell_output("#{bin}/story --version").strip
  end
end
