# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.js in danjdewhurst/story-skills. Do not edit:
# the release workflow rewrites it for every release.
class StorySkills < Formula
  desc "Companion CLI for Story Skills: validate, check, and build markdown story projects"
  homepage "https://github.com/danjdewhurst/story-skills"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.23.0/story-skills_0.23.0_darwin_arm64.tar.gz"
      sha256 "9261b2427ef5d63fc741e6f0bc536d5e921ffcdcd1fa12e41505a8b86aa89b85"
    end
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.23.0/story-skills_0.23.0_darwin_x64.tar.gz"
      sha256 "16fa8a50b603c8e97946c333172056926d8ae34bd6511d9f65d63cbb5db1c92b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.23.0/story-skills_0.23.0_linux_arm64.tar.gz"
      sha256 "dbb4b3082bf5c0182c2ecd256708930554a1f9aacdca3e902fa46743dd48d236"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.23.0/story-skills_0.23.0_linux_x64.tar.gz"
      sha256 "0b299c39442a9dec676da7e72e842a5607f3fd26f0a80bb4be364f287550f8bf"
    end
  end

  def install
    bin.install "story"
  end

  test do
    assert_equal "0.23.0", shell_output("#{bin}/story --version").strip
  end
end
