# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.js in danjdewhurst/story-skills. Do not edit:
# the release workflow rewrites it for every release.
class StorySkills < Formula
  desc "Companion CLI for Story Skills: validate, check, and build markdown story projects"
  homepage "https://github.com/danjdewhurst/story-skills"
  version "0.22.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.22.1/story-skills_0.22.1_darwin_arm64.tar.gz"
      sha256 "58df1f02cf9583081c21e970cba9093cbda0ac214e2951dcca0e4ef5245b2120"
    end
    if Hardware::CPU.intel?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.22.1/story-skills_0.22.1_darwin_x64.tar.gz"
      sha256 "fb963bf0be0e381b1fbf7d0c0d44b6d45be8e45b71f637fff240f2877c632545"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.22.1/story-skills_0.22.1_linux_arm64.tar.gz"
      sha256 "2fc97ec7a85a6cc9754b0e4df0d6f4996da42dfbc8e4fc03dcc2430cf136a5d7"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danjdewhurst/story-skills/releases/download/v0.22.1/story-skills_0.22.1_linux_x64.tar.gz"
      sha256 "e22bca802443391ea5c934a2550211b8379210c28809071a96a0af4631fbc3e1"
    end
  end

  def install
    bin.install "story"
  end

  test do
    assert_equal "0.22.1", shell_output("#{bin}/story --version").strip
  end
end
