# This file was generated by GoReleaser. DO NOT EDIT.
cask "jot-cli" do
  name "jot-cli"
  desc "A fast, context-aware notes tool for the terminal"
  homepage "https://github.com/danjdewhurst/jot-cli"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jot-cli"

  on_macos do
    on_intel do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "bc1c78206d9cba449092137018658e28df28c11e261c0269162e562938f7a628"
    end
    on_arm do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4750a9a95208b1dbb9e41921beb23a53ed50ae043845edd8c98add16022c6289"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_linux_amd64.tar.gz"
      sha256 "e27fc950e2230f6cb1021af38f4dde5ffe9ad3538a864336f5d5bbd08e3af305"
    end
    on_arm do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_linux_arm64.tar.gz"
      sha256 "4c91c863da23a226f9a0257f3dd366d8cc324c81818a0f47e39deae7600f4916"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jot-cli"]
    end
    system_command "/bin/ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/jot-cli", "#{HOMEBREW_PREFIX}/bin/j"]
  end

  # No zap stanza required
end
