# This file was generated by GoReleaser. DO NOT EDIT.
cask "jot-cli" do
  name "jot-cli"
  desc "A fast, context-aware notes tool for the terminal"
  homepage "https://github.com/danjdewhurst/jot-cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jot-cli"

  on_macos do
    on_intel do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "60feca7b7c52381bfb750a05d41685d6ffa44a791bbdbf8860cce02f6a26c823"
    end
    on_arm do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "2179e916a5f7c1e6381d5e513190a96567d2468c5cb409c9d8226c36a8c03cb6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_linux_amd64.tar.gz"
      sha256 "85e4ab74b6e6ecbe25e2f0b4b9031969bd3e4e5ddb37af40503b07bc2eddf80b"
    end
    on_arm do
      url "https://github.com/danjdewhurst/jot-cli/releases/download/v#{version}/jot-cli_#{version}_linux_arm64.tar.gz"
      sha256 "83d612c977cec9b11e280dced31f8080445abb529949a2e8ae5cb34cc431facc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jot-cli"]
    end
    system_command "/bin/ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/jot-cli", "#{HOMEBREW_PREFIX}/bin/j"]
  end

  # No zap stanza required
end
